import "./globals.css";
import { Inter } from "next/font/google";

import type { Metadata } from "next";

// These styles apply to every route in the application
import "./globals.css";
import { ApolloProviders, Providers } from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />
      <link rel="apple-touch-icon" href="/icon-512x512.png"></link>
      <meta name="theme-color" content="#000" />

      <body className={inter.className}>
        <Providers>
          <ApolloProviders>{children}</ApolloProviders>
        </Providers>
      </body>
    </html>
  );
}
